{{- if and .Values.kubelb.tunnel.enabled .Values.kubelb.tunnel.connectionManager.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: connection-manager-tls
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kubelb-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: tunnel-connection-manager
spec:
  secretName: connection-manager-tls
  issuerRef:
    name: {{ .Values.kubelb.tunnel.connectionManager.tls.issuer | default "letsencrypt-prod" }}
    kind: ClusterIssuer
  commonName: {{ .Values.kubelb.tunnel.connectionManager.tls.domain }}
  dnsNames:
    - {{ .Values.kubelb.tunnel.connectionManager.tls.domain }}
    - connection-manager.{{ .Release.Namespace }}
    - connection-manager.{{ .Release.Namespace }}.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
  duration: 720h    # 30 days
  renewBefore: 240h # 10 days
  usages:
    - digital signature
    - key encipherment
    - server auth
  privateKey:
    algorithm: RSA
    size: 2048
{{- end }}